fxp

diff --git a/.github/workflows/apigw-build-deploy.yml b/.github/workflows/apigw-build-deploy.yml
--- a/.github/workflows/apigw-build-deploy.yml
+++ b/.github/workflows/apigw-build-deploy.yml
@@ -3,9 +3,8 @@ name: Build and Deploy API Gateway
 on:
   push:
     branches:
-      - master
-    paths:
-      - 'apigw/**'
+      - main
+
   workflow_dispatch:  # umožňuje ruční spuštění deploy jobu
 
 jobs:
@@ -21,11 +20,8 @@ jobs:
         with:
           node-version: '20'
 
-      - name: Clean node_modules
-        run: rm -rf ${{ github.workspace }}/apigw/node_modules || true
-
       - name: Install dependencies
-        working-directory: ${{ github.workspace }}/apigw
+        working-directory: ${{ github.workspace }}
         run: yarn install || echo "Failed to install dependencies"
 
   build:
@@ -37,15 +33,13 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Build application
-        working-directory: ${{ github.workspace }}/apigw
-        env:
-          NODE_PATH: ${{ github.workspace }}/node_modules
-        run: yarn build || echo "Build failed"
+        working-directory: ${{ github.workspace }}
+        run: yarn apigw:build || echo "Build failed"
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    if: github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'workflow_dispatch'  # nasazení pouze při ručním spuštění
 
     steps:
       - name: Checkout repository
