f2

diff --git a/.github/workflows/apigw-build-deploy.yml b/.github/workflows/apigw-build-deploy.yml
--- a/.github/workflows/apigw-build-deploy.yml
+++ b/.github/workflows/apigw-build-deploy.yml
@@ -4,8 +4,9 @@ on:
   push:
     branches:
       - main
-
-  workflow_dispatch:  # umožňuje ruční spuštění deploy jobu
+    paths:
+      - '*'
+  workflow_dispatch:  # umožňuje manuální spuštění celého workflow
 
 jobs:
   prepare:
@@ -20,8 +21,11 @@ jobs:
         with:
           node-version: '20'
 
+      - name: Clean node_modules
+        run: rm -rf ${{ github.workspace }}/apigw/node_modules || true
+
       - name: Install dependencies
-        working-directory: ${{ github.workspace }}
+        working-directory: ${{ github.workspace }}/apigw
         run: yarn install || echo "Failed to install dependencies"
 
   build:
@@ -33,13 +37,13 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Build application
-        working-directory: ${{ github.workspace }}
-        run: yarn apigw:build || echo "Build failed"
+        working-directory: ${{ github.workspace }}/apigw
+        run: yarn build || echo "Build failed"
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    if: github.event_name == 'workflow_dispatch'  # nasazení pouze při ručním spuštění
+    if: github.event_name == 'workflow_dispatch'  # nasazení pouze při manuálním spuštění
 
     steps:
       - name: Checkout repository
