test2

diff --git a/.github/workflows/apigw-build-deploy.yml b/.github/workflows/apigw-build-deploy.yml
--- a/.github/workflows/apigw-build-deploy.yml
+++ b/.github/workflows/apigw-build-deploy.yml
@@ -1,31 +1,49 @@
-name: Node.js CI
-
+name: APIGW Build & Deploy
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        node-version: [ 20 ]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Build APIGW
+        uses: actions/setup-node@v2
+        with:
+          node-version: 20
+
+      - name: Install dependencies
+        run: yarn
+
+      - name: Build project
+        run: yarn apigw:build
+
+      - name: Check build success
+        if: ${{ failure() }}
+        run: |
+          echo "Build failed!"
+          exit 1
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.event_name == 'workflow_dispatch'
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Setup Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v2
-      with:
-        node-version: ${{ matrix.node-version }}
-
-    - name: Install dependencies
-      run: yarn
-
-    - name: Build project
-      run: yarn apigw:build
+      - name: Deploy to Render
+        env:
+          APIGW_DEPLOY_APIKEY: ${{ secrets.APIGW_DEPLOY_APIKEY }}
+          APIGW_DEPLOY_SERVICE_ID: ${{ secrets.APIGW_DEPLOY_SERVICE_ID }}
+          APIGW_DEPLOY_HOOK_SECRET: ${{ secrets.APIGW_DEPLOY_HOOK_SECRET }}
+        run: |
+          echo "Deploying APIGW to Render"
+          curl -X POST https://api.render.com/deploy/srv-$APIGW_DEPLOY_SERVICE_ID?key=$APIGW_DEPLOY_HOOK_SECRET
